#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://docs.travis-ci.com/user/languages/php/ for more hints
#
language: php

# use container based infrastructure (no sudo possible)
sudo: false

php: [7.1, 7.2, 7.3]

matrix:
    allow_failures:
        - php: 7.1

script:
 - php test/all_tests.php

# disable notifications
notifications:
  email: false

# reduce commit history of git checkout
git:
  depth: 5